

#           Copyright Nathaniel Christen 2019.
#  Distributed under the Boost Software License, Version 1.0.
#     (See accompanying file LICENSE_1_0.txt or copy at
#           http://www.boost.org/LICENSE_1_0.txt)

include(../build-group.pri)


INCLUDEPATH += $$SRC_DIR

DEFINES += ROOT_FOLDER=\\\"$$ROOT_DIR\\\"



#HEADERS += \
#  $$SRC_DIR/mainwindow.h\

#SOURCES += \
#  $$SRC_DIR/main.cpp\


# #  for dcmtk OFString = std::string ...
DEFINES += HAVE_STD_STRING
DEFINES += HAVE_STL_STRING


LIBS += -L$$TARGETSDIR  -lofstd  -ldcmsr -loflog -ldcmdata \
   -ldcmimage -ldcmimgle

# #  assumed xerces is installed ...
LIBS += -lxerces-c

# LIBS += -L$$SRC_DIR/xercesc-3.1/x86/lib -lxerces-c_3D


DCMTK_DIR = $$DCMTK_SRC_GROUP_DIR


INCLUDEPATH += $$DCMTK_DIR/ofstd/include
INCLUDEPATH += $$DCMTK_DIR/dcm-config/include
INCLUDEPATH += $$DCMTK_DIR/dcmsr/include
INCLUDEPATH += $$DCMTK_DIR/dcmdata/include
INCLUDEPATH += $$DCMTK_DIR/oflog/include


HEADERS += \
  $$SRC_DIR/AIMLib/AIMConverter/AIMConverter.h \
  $$SRC_DIR/AIMLib/AIMConverter/ConverterUtil.h \
  $$SRC_DIR/AIMLib/AIMConverter/stdafx.h \
  $$SRC_DIR/AIMLib/AIMLib/AIMCodes.h \
  $$SRC_DIR/AIMLib/AIMLib/AIMCommon.h \
  $$SRC_DIR/AIMLib/AIMLib/AIMLib.h \
  $$SRC_DIR/AIMLib/AIMLib/AIMUtil.h \
  $$SRC_DIR/AIMLib/AIMLib/AimEnum.h \
  $$SRC_DIR/AIMLib/AIMLib/AimHeaders.h \
  $$SRC_DIR/AIMLib/AIMLib/AimResultValidator.h \
  $$SRC_DIR/AIMLib/AIMLib/entity/AdjudicationObservation.h \
  $$SRC_DIR/AIMLib/AIMLib/entity/Algorithm.h \
  $$SRC_DIR/AIMLib/AIMLib/entity/AnnotationCollection.h \
  $$SRC_DIR/AIMLib/AIMLib/entity/AnnotationEntity.h \
  $$SRC_DIR/AIMLib/AIMLib/entity/AnnotationOfAnnotation.h \
  $$SRC_DIR/AIMLib/AIMLib/entity/AnnotationOfAnnotationCollection.h \
  $$SRC_DIR/AIMLib/AIMLib/entity/AnnotationRoleEntity.h \
  $$SRC_DIR/AIMLib/AIMLib/entity/AuditTrail.h \
  $$SRC_DIR/AIMLib/AIMLib/entity/CalculationData.h \
  $$SRC_DIR/AIMLib/AIMLib/entity/CalculationEntity.h \
  $$SRC_DIR/AIMLib/AIMLib/entity/CalculationResult.h \
  $$SRC_DIR/AIMLib/AIMLib/entity/CharacteristicQuantification.h \
  $$SRC_DIR/AIMLib/AIMLib/entity/CompactCalculationResult.h \
  $$SRC_DIR/AIMLib/AIMLib/entity/Coordinate.h \
  $$SRC_DIR/AIMLib/AIMLib/entity/DicomImageReferenceEntity.h \
  $$SRC_DIR/AIMLib/AIMLib/entity/DicomSegmentationEntity.h \
  $$SRC_DIR/AIMLib/AIMLib/entity/Dimension.h \
  $$SRC_DIR/AIMLib/AIMLib/entity/Entity.h \
  $$SRC_DIR/AIMLib/AIMLib/entity/Equipment.h \
  $$SRC_DIR/AIMLib/AIMLib/entity/ExtendedCalculationResult.h \
  $$SRC_DIR/AIMLib/AIMLib/entity/GeneralImage.h \
  $$SRC_DIR/AIMLib/AIMLib/entity/GeneralLesionObservationEntity.h \
  $$SRC_DIR/AIMLib/AIMLib/entity/GeometricShapeEntity.h \
  $$SRC_DIR/AIMLib/AIMLib/entity/Image.h \
  $$SRC_DIR/AIMLib/AIMLib/entity/ImageAnnotation.h \
  $$SRC_DIR/AIMLib/AIMLib/entity/ImageAnnotationCollection.h \
  $$SRC_DIR/AIMLib/AIMLib/entity/ImagePlane.h \
  $$SRC_DIR/AIMLib/AIMLib/entity/ImageReferenceEntity.h \
  $$SRC_DIR/AIMLib/AIMLib/entity/ImageSeries.h \
  $$SRC_DIR/AIMLib/AIMLib/entity/ImageStudy.h \
  $$SRC_DIR/AIMLib/AIMLib/entity/ImagingObservationCharacteristic.h \
  $$SRC_DIR/AIMLib/AIMLib/entity/ImagingObservationEntity.h \
  $$SRC_DIR/AIMLib/AIMLib/entity/ImagingPhysicalEntity.h \
  $$SRC_DIR/AIMLib/AIMLib/entity/ImagingPhysicalEntityCharacteristic.h \
  $$SRC_DIR/AIMLib/AIMLib/entity/InferenceEntity.h \
  $$SRC_DIR/AIMLib/AIMLib/entity/Interval.h \
  $$SRC_DIR/AIMLib/AIMLib/entity/LesionObservationEntity.h \
  $$SRC_DIR/AIMLib/AIMLib/entity/MarkupEntity.h \
  $$SRC_DIR/AIMLib/AIMLib/entity/NonQuantifiable.h \
  $$SRC_DIR/AIMLib/AIMLib/entity/Numerical.h \
  $$SRC_DIR/AIMLib/AIMLib/entity/Parameter.h \
  $$SRC_DIR/AIMLib/AIMLib/entity/Person.h \
  $$SRC_DIR/AIMLib/AIMLib/entity/Quantile.h \
  $$SRC_DIR/AIMLib/AIMLib/entity/ReferencedDicomObject.h \
  $$SRC_DIR/AIMLib/AIMLib/entity/Scale.h \
  $$SRC_DIR/AIMLib/AIMLib/entity/SegmentationEntity.h \
  $$SRC_DIR/AIMLib/AIMLib/entity/TaskContextEntity.h \
  $$SRC_DIR/AIMLib/AIMLib/entity/TextAnnotationEntity.h \
  $$SRC_DIR/AIMLib/AIMLib/entity/ThreeDimensionEllipse.h \
  $$SRC_DIR/AIMLib/AIMLib/entity/ThreeDimensionEllipsoid.h \
  $$SRC_DIR/AIMLib/AIMLib/entity/ThreeDimensionGeometricShapeEntity.h \
  $$SRC_DIR/AIMLib/AIMLib/entity/ThreeDimensionMultiPoint.h \
  $$SRC_DIR/AIMLib/AIMLib/entity/ThreeDimensionPoint.h \
  $$SRC_DIR/AIMLib/AIMLib/entity/ThreeDimensionPolygon.h \
  $$SRC_DIR/AIMLib/AIMLib/entity/ThreeDimensionPolyline.h \
  $$SRC_DIR/AIMLib/AIMLib/entity/ThreeDimensionSpatialCoordinate.h \
  $$SRC_DIR/AIMLib/AIMLib/entity/TimePointLesionObservationEntity.h \
  $$SRC_DIR/AIMLib/AIMLib/entity/TwoDimensionCircle.h \
  $$SRC_DIR/AIMLib/AIMLib/entity/TwoDimensionEllipse.h \
  $$SRC_DIR/AIMLib/AIMLib/entity/TwoDimensionGeometricShapeEntity.h \
  $$SRC_DIR/AIMLib/AIMLib/entity/TwoDimensionMultiPoint.h \
  $$SRC_DIR/AIMLib/AIMLib/entity/TwoDimensionPoint.h \
  $$SRC_DIR/AIMLib/AIMLib/entity/TwoDimensionPolyline.h \
  $$SRC_DIR/AIMLib/AIMLib/entity/TwoDimensionSpatialCoordinate.h \
  $$SRC_DIR/AIMLib/AIMLib/entity/UriImageReferenceEntity.h \
  $$SRC_DIR/AIMLib/AIMLib/entity/User.h \
  $$SRC_DIR/AIMLib/AIMLib/external/CD.h \
  $$SRC_DIR/AIMLib/AIMLib/external/II.h \
  $$SRC_DIR/AIMLib/AIMLib/memdebug.h \
  $$SRC_DIR/AIMLib/AIMLib/operations/BaseModel.h \
  $$SRC_DIR/AIMLib/AIMLib/operations/DcmModel.h \
  $$SRC_DIR/AIMLib/AIMLib/operations/DcmModelInternal.h \
  $$SRC_DIR/AIMLib/AIMLib/operations/DicomTagCollection.h \
  $$SRC_DIR/AIMLib/AIMLib/operations/ModelValidator.h \
  $$SRC_DIR/AIMLib/AIMLib/operations/XmlModel.h \
  $$SRC_DIR/AIMLib/AIMLib/operations/XmlModelInternal.h \
  $$SRC_DIR/AIMLib/AIMLib/statement/AbstractAnnotationStatement.h \
  $$SRC_DIR/AIMLib/AIMLib/statement/AnnotationOfAnnotationStatement.h \
  $$SRC_DIR/AIMLib/AIMLib/statement/AnnotationStatement.h \
  $$SRC_DIR/AIMLib/AIMLib/statement/AnnotationStatementRelationship.h \
  $$SRC_DIR/AIMLib/AIMLib/statement/ImageAnnotationStatement.h \
  $$SRC_DIR/AIMLib/AIMLib/statement/StatementFactory.h \
  $$SRC_DIR/AIMLib/AIMLib/stdafx.h \
  $$SRC_DIR/AIMLib/AIMLib/util/AimUidGenerator.h \
  $$SRC_DIR/AIMLib/AIMLib/util/DateTime.h \
  $$SRC_DIR/AIMLib/AIMXML/AIMXML-typeinfo.h \
  $$SRC_DIR/AIMLib/AIMXML/AIMXML.h \
  $$SRC_DIR/AIMLib/AIMXML/StdAfx.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CAIMXML.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CAdjudicationObservation.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CAimVersion.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CAlgorithm.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CAnnotationCollection.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CAnnotationEntity.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CAnnotationEntityHasPerformedTaskContextEntityStatement.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CAnnotationEntityHasPlannedTaskContextEntityStatement.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CAnnotationOfAnnotation.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CAnnotationOfAnnotationCollection.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CAnnotationOfAnnotationHasAnnotationOfAnnotationStatement.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CAnnotationOfAnnotationHasAnnotationRoleEntityStatement.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CAnnotationOfAnnotationHasCalculationEntityStatement.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CAnnotationOfAnnotationHasGeneralLesionObservationEntityStatement.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CAnnotationOfAnnotationHasImageAnnotationStatement.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CAnnotationOfAnnotationHasImagingObservationEntityStatement.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CAnnotationOfAnnotationHasImagingPhysicalEntityStatement.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CAnnotationOfAnnotationHasInferenceEntityStatement.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CAnnotationOfAnnotationHasTimePointLesionObservationEntityStatement.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CAnnotationOfAnnotationIsComparedWithAnnotationOfAnnotationStatement.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CAnnotationOfAnnotationIsComparedWithImageAnnotationStatement.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CAnnotationOfAnnotationStatement.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CAnnotationRoleEntity.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CAnnotationStatement.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CAuditTrail.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CCalculationData.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CCalculationEntity.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CCalculationEntityIsComparedWithCalculationEntityStatement.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CCalculationEntityReferencesCalculationEntityStatement.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CCalculationEntityUsesCalculationEntityStatement.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CCalculationResult.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CCalculationResultIdentifier.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CCharacteristicQuantification.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CCompactCalculationResult.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CComparisonOperator.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CCoordinate.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CDicomImageReferenceEntity.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CDicomImageReferenceEntityHasCalculationEntityStatement.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CDicomImageReferenceEntityHasImagingObservationEntityStatement.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CDicomImageReferenceEntityHasImagingPhysicalEntityStatement.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CDicomSegmentationEntity.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CDicomSegmentationEntityHasImagingObservationEntityStatement.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CDimension.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CEntity.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CEquipment.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CExtendedCalculationResult.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CGeneralImage.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CGeneralLesionObservationEntity.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CGeneralLesionObservationEntityHasImagingPhysicalEntityStatement.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CGeometricShapeEntity.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CImage.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CImageAnnotation.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CImageAnnotationCollection.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CImageAnnotationHasAnnotationRoleEntityStatement.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CImageAnnotationHasCalculationEntityStatement.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CImageAnnotationHasChildImageAnnotationStatement.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CImageAnnotationHasDicomImageReferenceEntityStatement.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CImageAnnotationHasDicomSegmentationEntityStatement.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CImageAnnotationHasGeneralLesionObservationEntityStatement.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CImageAnnotationHasImagingObservationEntityStatement.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CImageAnnotationHasImagingPhysicalEntityStatement.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CImageAnnotationHasInferenceEntityStatement.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CImageAnnotationHasTextAnnotationEntityStatement.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CImageAnnotationHasThreeDimensionGeometricShapeEntityStatement.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CImageAnnotationHasTimePointLesionObservationEntityStatement.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CImageAnnotationHasTwoDimensionGeometricShapeEntityStatement.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CImageAnnotationHasUriImageReferenceEntityStatement.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CImageAnnotationIsComparedWithAnnotationOfAnnotationStatement.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CImageAnnotationIsComparedWithImageAnnotationStatement.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CImageAnnotationStatement.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CImagePlane.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CImageReferenceEntity.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CImageSeries.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CImageStudy.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CImagingObservationCharacteristic.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CImagingObservationEntity.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CImagingObservationEntityHasCalculationEntityStatement.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CImagingObservationEntityIsFoundInImagingPhysicalEntityStatement.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CImagingObservationEntityIsIdentifiedByTextAnnotationEntityStatement.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CImagingObservationEntityIsIdentifiedByThreeDimensionGeometricShapeEntityStatement.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CImagingObservationEntityIsIdentifiedByTwoDimensionGeometricShapeEntityStatement.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CImagingPhysicalEntity.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CImagingPhysicalEntityCharacteristic.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CImagingPhysicalEntityHasCalculationEntityStatement.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CImagingPhysicalEntityHasImagingObservationEntityStatement.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CImagingPhysicalEntityHasTextAnnotationEntityStatement.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CImagingPhysicalEntityHasThreeDimensionGeometricShapeEntityStatement.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CImagingPhysicalEntityHasTwoDimensionGeometricShapeEntityStatement.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CInferenceEntity.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CInterval.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CLesionObservationEntity.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CMarkupEntity.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CNonQuantifiable.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CNumerical.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CParameter.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CPerson.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CQuantile.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CReferencedDicomObject.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CScale.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CScaleType.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CSegmentationEntity.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CTaskContextEntity.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CTextAnnotationEntity.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CThreeDimensionEllipse.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CThreeDimensionEllipsoid.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CThreeDimensionGeometricShapeEntity.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CThreeDimensionGeometricShapeEntityExcludesThreeDimensionGeometricShapeEntityStatement.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CThreeDimensionGeometricShapeEntityIsComprisedOfThreeDimensionGeometricShapeEntityStatement.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CThreeDimensionMultiPoint.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CThreeDimensionPoint.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CThreeDimensionPolygon.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CThreeDimensionPolyline.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CThreeDimensionSpatialCoordinate.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CTimePointLesionObservationEntity.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CTimePointLesionObservationEntityHasImagingPhysicalEntityStatement.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CTwoDimensionCircle.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CTwoDimensionEllipse.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CTwoDimensionGeometricShapeEntity.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CTwoDimensionGeometricShapeEntityExcludesTwoDimensionGeometricShapeEntityStatement.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CTwoDimensionGeometricShapeEntityIsComprisedOfTwoDimensionGeometricShapeEntityStatement.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CTwoDimensionMultiPoint.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CTwoDimensionPoint.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CTwoDimensionPolyline.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CTwoDimensionSpatialCoordinate.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CUriImageReferenceEntity.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CUriImageReferenceEntityHasCalculationEntityStatement.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CUriImageReferenceEntityHasImagingObservationEntityStatement.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CUriImageReferenceEntityHasImagingPhysicalEntityStatement.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CUser.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CalignType.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CalignType2.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CalignType3.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CalignType4.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CalignType5.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CalignType6.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CalignType7.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CalignType8.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CannotationOfAnnotationStatementCollectionType.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CannotationOfAnnotationsType.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CannotationRoleEntityCollectionType.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CauditTrailCollectionType.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CbrType.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CcalculationDataCollectionType.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CcalculationEntityCollectionType.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CcalculationResultCollectionType.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CcaptionType.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CcharacteristicQuantificationCollectionType.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CcharacteristicQuantificationCollectionType2.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CcolType.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CcolgroupType.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CcontentType.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CcoordinateCollectionType.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CdimensionCollectionType.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CfootnoteRefType.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CfootnoteType.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CframeType.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CimageAnnotationStatementCollectionType.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CimageAnnotationsType.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CimageCollectionType.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CimageReferenceEntityCollectionType.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CimagingObservationCharacteristicCollectionType.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CimagingObservationCharacteristicCollectionType2.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CimagingObservationEntityCollectionType.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CimagingPhysicalEntityCharacteristicCollectionType.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CimagingPhysicalEntityCollectionType.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CinferenceEntityCollectionType.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CitemType.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.ClesionObservationEntityCollectionType.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.ClinkHtmlType.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.ClistType.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.ClistTypeType.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CmarkupEntityCollectionType.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CparagraphType.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CparameterCollectionType.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CreferencedDicomObjectCollectionType.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CrenderMultiMediaType.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CrevisedType.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CrulesType.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CscopeType.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CscopeType2.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CsegmentationEntityCollectionType.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CtableType.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CtaskContextEntityCollectionType.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CtaskContextEntityCollectionType2.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CtbodyType.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CtdType.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CtfootType.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CthType.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CtheadType.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CthreeDimensionSpatialCoordinateCollectionType.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CtrType.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CtwoDimensionSpatialCoordinateCollectionType.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CvalignType.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CvalignType2.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CvalignType3.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CvalignType4.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CvalignType5.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CvalignType6.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CvalignType7.h \
  $$SRC_DIR/AIMLib/AIMXML/type_.CvalignType8.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CAD.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CADXP.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CANY.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CAddressPartType.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CBAG_AD.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CBAG_BL.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CBAG_BL_NonNull.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CBAG_CD.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CBAG_CD_CE.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CBAG_CD_CE_None.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CBAG_CD_CV.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CBAG_CO.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CBAG_CS.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CBAG_ED.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CBAG_ED_Doc.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CBAG_ED_Doc_Inline.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CBAG_ED_Doc_Ref.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CBAG_ED_Image.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CBAG_ED_Narrative.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CBAG_ED_Signature.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CBAG_ED_Text.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CBAG_EN.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CBAG_EN_ON.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CBAG_EN_PN.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CBAG_EN_TN.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CBAG_II.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CBAG_INT.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CBAG_INT_NonNeg.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CBAG_INT_Positive.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CBAG_MO.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CBAG_PQ.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CBAG_PQ_Time.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CBAG_REAL.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CBAG_RTO.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CBAG_SC.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CBAG_SC_NT.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CBAG_ST.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CBAG_ST_NT.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CBAG_TEL.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CBAG_TEL_Email.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CBAG_TEL_Person.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CBAG_TEL_Phone.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CBAG_TEL_Url.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CBAG_TS.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CBAG_TS_Birth.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CBAG_TS_Date.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CBAG_TS_DateTime.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CBAG_TS_DateTime_Full.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CBAG_TS_Date_Full.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CBL.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CBL_NonNull.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CCD.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CCDGroup.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CCD_CE.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CCD_CE_None.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CCD_CV.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CCO.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CCOLL_AD.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CCOLL_BL.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CCOLL_BL_NonNull.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CCOLL_CD.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CCOLL_CD_CE.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CCOLL_CD_CE_None.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CCOLL_CD_CV.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CCOLL_CO.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CCOLL_CS.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CCOLL_ED.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CCOLL_ED_Doc.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CCOLL_ED_Doc_Inline.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CCOLL_ED_Doc_Ref.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CCOLL_ED_Image.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CCOLL_ED_Narrative.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CCOLL_ED_Signature.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CCOLL_ED_Text.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CCOLL_EN.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CCOLL_EN_ON.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CCOLL_EN_PN.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CCOLL_EN_TN.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CCOLL_II.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CCOLL_INT.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CCOLL_INT_NonNeg.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CCOLL_INT_Positive.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CCOLL_MO.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CCOLL_PQ.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CCOLL_PQ_Time.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CCOLL_REAL.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CCOLL_RTO.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CCOLL_SC.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CCOLL_SC_NT.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CCOLL_ST.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CCOLL_ST_NT.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CCOLL_TEL.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CCOLL_TEL_Email.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CCOLL_TEL_Person.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CCOLL_TEL_Phone.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CCOLL_TEL_Url.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CCOLL_TS.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CCOLL_TS_Birth.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CCOLL_TS_Date.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CCOLL_TS_DateTime.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CCOLL_TS_DateTime_Full.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CCOLL_TS_Date_Full.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CCR.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CCS.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CCalendarCycle.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CCode.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CCodingRationale.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CCompression.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CDSET_AD.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CDSET_BL.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CDSET_BL_NonNull.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CDSET_CD.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CDSET_CD_CE.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CDSET_CD_CE_None.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CDSET_CD_CV.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CDSET_CO.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CDSET_CS.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CDSET_ED.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CDSET_ED_Doc.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CDSET_ED_Doc_Inline.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CDSET_ED_Doc_Ref.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CDSET_ED_Image.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CDSET_ED_Narrative.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CDSET_ED_Signature.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CDSET_ED_Text.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CDSET_EN.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CDSET_EN_ON.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CDSET_EN_PN.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CDSET_EN_TN.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CDSET_II.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CDSET_INT.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CDSET_INT_NonNeg.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CDSET_INT_Positive.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CDSET_MO.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CDSET_PQ.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CDSET_PQ_Time.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CDSET_REAL.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CDSET_RTO.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CDSET_SC.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CDSET_SC_NT.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CDSET_ST.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CDSET_ST_NT.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CDSET_TEL.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CDSET_TEL_Email.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CDSET_TEL_Person.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CDSET_TEL_Phone.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CDSET_TEL_Url.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CDSET_TS.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CDSET_TS_Birth.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CDSET_TS_Date.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CDSET_TS_DateTime.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CDSET_TS_DateTime_Full.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CDSET_TS_Date_Full.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CED.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CED_Doc.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CED_Doc_Inline.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CED_Doc_Ref.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CED_Image.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CED_Narrative.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CED_Signature.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CED_Text.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CEIVL_TS.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CEIVL_TS_Birth.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CEIVL_TS_Date.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CEIVL_TS_DateTime.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CEIVL_TS_DateTime_Full.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CEIVL_TS_Date_Full.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CEN.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CENXP.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CEN_ON.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CEN_PN.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CEN_TN.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CEntityNamePartQualifier.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CEntityNamePartType.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CEntityNameUse.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CGLIST_CO.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CGLIST_INT.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CGLIST_INT_NonNeg.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CGLIST_INT_Positive.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CGLIST_MO.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CGLIST_PQ.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CGLIST_PQ_Time.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CGLIST_REAL.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CGLIST_RTO.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CGLIST_TS.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CGLIST_TS_Birth.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CGLIST_TS_Date.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CGLIST_TS_DateTime.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CGLIST_TS_DateTime_Full.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CGLIST_TS_Date_Full.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CHIST_AD.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CHIST_BL.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CHIST_BL_NonNull.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CHIST_CD.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CHIST_CD_CE.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CHIST_CD_CE_None.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CHIST_CD_CV.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CHIST_CO.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CHIST_CS.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CHIST_ED.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CHIST_ED_Doc.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CHIST_ED_Doc_Inline.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CHIST_ED_Doc_Ref.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CHIST_ED_Image.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CHIST_ED_Narrative.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CHIST_ED_Signature.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CHIST_ED_Text.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CHIST_EN.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CHIST_EN_ON.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CHIST_EN_PN.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CHIST_EN_TN.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CHIST_II.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CHIST_INT.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CHIST_INT_NonNeg.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CHIST_INT_Positive.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CHIST_MO.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CHIST_PQ.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CHIST_PQ_Time.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CHIST_REAL.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CHIST_RTO.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CHIST_SC.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CHIST_SC_NT.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CHIST_ST.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CHIST_ST_NT.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CHIST_TEL.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CHIST_TEL_Email.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CHIST_TEL_Person.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CHIST_TEL_Phone.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CHIST_TEL_Url.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CHIST_TS.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CHIST_TS_Birth.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CHIST_TS_Date.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CHIST_TS_DateTime.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CHIST_TS_DateTime_Full.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CHIST_TS_Date_Full.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CHXIT.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CII.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CINT.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CINT_NonNeg.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CINT_Positive.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CIVL_CO.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CIVL_High_CO.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CIVL_High_INT.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CIVL_High_INT_NonNeg.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CIVL_High_INT_Positive.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CIVL_High_MO.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CIVL_High_PQ.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CIVL_High_PQ_Time.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CIVL_High_REAL.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CIVL_High_RTO.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CIVL_High_TS.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CIVL_High_TS_Birth.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CIVL_High_TS_Date.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CIVL_High_TS_DateTime.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CIVL_High_TS_DateTime_Full.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CIVL_High_TS_Date_Full.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CIVL_INT.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CIVL_INT_NonNeg.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CIVL_INT_Positive.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CIVL_Low_CO.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CIVL_Low_INT.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CIVL_Low_INT_NonNeg.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CIVL_Low_INT_Positive.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CIVL_Low_MO.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CIVL_Low_PQ.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CIVL_Low_PQ_Time.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CIVL_Low_REAL.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CIVL_Low_RTO.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CIVL_Low_TS.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CIVL_Low_TS_Birth.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CIVL_Low_TS_Date.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CIVL_Low_TS_DateTime.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CIVL_Low_TS_DateTime_Full.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CIVL_Low_TS_Date_Full.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CIVL_MO.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CIVL_PQ.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CIVL_PQ_Time.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CIVL_REAL.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CIVL_RTO.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CIVL_TS.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CIVL_TS_Birth.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CIVL_TS_Date.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CIVL_TS_DateTime.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CIVL_TS_DateTime_Full.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CIVL_TS_Date_Full.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CIVL_Width_CO.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CIVL_Width_INT.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CIVL_Width_INT_NonNeg.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CIVL_Width_INT_Positive.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CIVL_Width_MO.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CIVL_Width_PQ.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CIVL_Width_PQ_Time.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CIVL_Width_REAL.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CIVL_Width_RTO.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CIVL_Width_TS.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CIVL_Width_TS_Birth.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CIVL_Width_TS_Date.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CIVL_Width_TS_DateTime.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CIVL_Width_TS_DateTime_Full.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CIVL_Width_TS_Date_Full.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CIdentifierReliability.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CIdentifierScope.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CIntegrityCheckAlgorithm.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CLIST_AD.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CLIST_BL.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CLIST_BL_NonNull.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CLIST_CD.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CLIST_CD_CE.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CLIST_CD_CE_None.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CLIST_CD_CV.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CLIST_CO.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CLIST_CS.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CLIST_ED.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CLIST_ED_Doc.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CLIST_ED_Doc_Inline.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CLIST_ED_Doc_Ref.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CLIST_ED_Image.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CLIST_ED_Narrative.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CLIST_ED_Signature.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CLIST_ED_Text.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CLIST_EN.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CLIST_EN_ON.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CLIST_EN_PN.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CLIST_EN_TN.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CLIST_II.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CLIST_INT.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CLIST_INT_NonNeg.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CLIST_INT_Positive.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CLIST_MO.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CLIST_PQ.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CLIST_PQ_Time.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CLIST_REAL.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CLIST_RTO.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CLIST_SC.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CLIST_SC_NT.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CLIST_ST.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CLIST_ST_NT.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CLIST_TEL.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CLIST_TEL_Email.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CLIST_TEL_Person.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CLIST_TEL_Phone.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CLIST_TEL_Url.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CLIST_TS.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CLIST_TS_Birth.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CLIST_TS_Date.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CLIST_TS_DateTime.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CLIST_TS_DateTime_Full.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CLIST_TS_Date_Full.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CMO.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CNPPD_AD.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CNPPD_BL.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CNPPD_BL_NonNull.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CNPPD_CD.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CNPPD_CD_CE.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CNPPD_CD_CE_None.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CNPPD_CD_CV.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CNPPD_CO.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CNPPD_CS.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CNPPD_ED.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CNPPD_ED_Doc.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CNPPD_ED_Doc_Inline.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CNPPD_ED_Doc_Ref.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CNPPD_ED_Image.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CNPPD_ED_Narrative.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CNPPD_ED_Signature.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CNPPD_ED_Text.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CNPPD_EN.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CNPPD_EN_ON.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CNPPD_EN_PN.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CNPPD_EN_TN.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CNPPD_II.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CNPPD_INT.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CNPPD_INT_NonNeg.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CNPPD_INT_Positive.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CNPPD_MO.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CNPPD_PQ.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CNPPD_PQ_Time.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CNPPD_REAL.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CNPPD_RTO.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CNPPD_SC.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CNPPD_SC_NT.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CNPPD_ST.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CNPPD_ST_NT.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CNPPD_TEL.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CNPPD_TEL_Email.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CNPPD_TEL_Person.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CNPPD_TEL_Phone.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CNPPD_TEL_Url.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CNPPD_TS.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CNPPD_TS_Birth.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CNPPD_TS_Date.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CNPPD_TS_DateTime.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CNPPD_TS_DateTime_Full.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CNPPD_TS_Date_Full.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CNarrative.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CNullFlavor.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CPIVL_TS.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CPIVL_TS_Birth.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CPIVL_TS_Date.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CPIVL_TS_DateTime.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CPIVL_TS_DateTime_Full.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CPIVL_TS_Date_Full.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CPQ.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CPQR.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CPQ_Time.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CPostalAddressUse.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CQSD_CO.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CQSD_INT.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CQSD_INT_NonNeg.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CQSD_INT_Positive.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CQSD_MO.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CQSD_PQ.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CQSD_PQ_Time.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CQSD_REAL.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CQSD_RTO.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CQSD_TS.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CQSD_TS_Birth.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CQSD_TS_Date.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CQSD_TS_DateTime.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CQSD_TS_DateTime_Full.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CQSD_TS_Date_Full.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CQSET_BoundedPIVL.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CQSET_CO.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CQSET_INT.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CQSET_INT_NonNeg.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CQSET_INT_Positive.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CQSET_MO.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CQSET_PQ.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CQSET_PQ_Time.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CQSET_REAL.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CQSET_RTO.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CQSET_TS.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CQSET_TS_Birth.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CQSET_TS_Date.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CQSET_TS_DateTime.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CQSET_TS_DateTime_Full.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CQSET_TS_Date_Full.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CQSI_CO.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CQSI_INT.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CQSI_INT_NonNeg.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CQSI_INT_Positive.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CQSI_MO.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CQSI_PQ.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CQSI_PQ_Time.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CQSI_REAL.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CQSI_RTO.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CQSI_TS.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CQSI_TS_Birth.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CQSI_TS_Date.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CQSI_TS_DateTime.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CQSI_TS_DateTime_Full.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CQSI_TS_Date_Full.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CQSP_CO.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CQSP_INT.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CQSP_INT_NonNeg.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CQSP_INT_Positive.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CQSP_MO.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CQSP_PQ.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CQSP_PQ_Time.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CQSP_REAL.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CQSP_RTO.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CQSP_TS.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CQSP_TS_Birth.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CQSP_TS_Date.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CQSP_TS_DateTime.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CQSP_TS_DateTime_Full.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CQSP_TS_Date_Full.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CQSS_CO.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CQSS_INT.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CQSS_INT_NonNeg.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CQSS_INT_Positive.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CQSS_MO.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CQSS_PQ.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CQSS_PQ_Time.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CQSS_REAL.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CQSS_RTO.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CQSS_TS.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CQSS_TS_Birth.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CQSS_TS_Date.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CQSS_TS_DateTime.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CQSS_TS_DateTime_Full.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CQSS_TS_Date_Full.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CQSU_CO.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CQSU_INT.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CQSU_INT_NonNeg.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CQSU_INT_Positive.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CQSU_MO.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CQSU_PQ.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CQSU_PQ_Time.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CQSU_REAL.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CQSU_RTO.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CQSU_TS.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CQSU_TS_Birth.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CQSU_TS_Date.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CQSU_TS_DateTime.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CQSU_TS_DateTime_Full.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CQSU_TS_Date_Full.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CQTY.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CREAL.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CRTO.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CSC.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CSC_NT.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CSLIST_CO.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CSLIST_INT.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CSLIST_INT_NonNeg.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CSLIST_INT_Positive.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CSLIST_MO.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CSLIST_PQ.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CSLIST_PQ_Time.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CSLIST_REAL.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CSLIST_RTO.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CSLIST_TS.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CSLIST_TS_Birth.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CSLIST_TS_Date.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CSLIST_TS_DateTime.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CSLIST_TS_DateTime_Full.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CSLIST_TS_Date_Full.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CST.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CST_NT.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CTEL.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CTEL_Email.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CTEL_Person.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CTEL_Phone.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CTEL_Url.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CTS.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CTS_Birth.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CTS_Date.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CTS_DateTime.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CTS_DateTime_Full.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CTS_Date_Full.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CTelecommunicationAddressUse.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CTimingEvent.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CURL.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CUVP_AD.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CUVP_BL.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CUVP_BL_NonNull.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CUVP_CD.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CUVP_CD_CE.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CUVP_CD_CE_None.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CUVP_CD_CV.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CUVP_CO.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CUVP_CS.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CUVP_ED.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CUVP_ED_Doc.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CUVP_ED_Doc_Inline.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CUVP_ED_Doc_Ref.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CUVP_ED_Image.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CUVP_ED_Narrative.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CUVP_ED_Signature.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CUVP_ED_Text.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CUVP_EN.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CUVP_EN_ON.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CUVP_EN_PN.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CUVP_EN_TN.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CUVP_II.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CUVP_INT.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CUVP_INT_NonNeg.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CUVP_INT_Positive.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CUVP_MO.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CUVP_PQ.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CUVP_PQ_Time.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CUVP_REAL.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CUVP_RTO.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CUVP_SC.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CUVP_SC_NT.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CUVP_ST.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CUVP_ST_NT.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CUVP_TEL.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CUVP_TEL_Email.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CUVP_TEL_Person.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CUVP_TEL_Phone.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CUVP_TEL_Url.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CUVP_TS.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CUVP_TS_Birth.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CUVP_TS_Date.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CUVP_TS_DateTime.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CUVP_TS_DateTime_Full.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CUVP_TS_Date_Full.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CUid.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CUncertaintyType.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CUpdateMode.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CUri.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.CXReference.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.Cset_CodingRationale.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.Cset_EntityNamePartQualifier.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.Cset_EntityNameUse.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.Cset_PostalAddressUse.h \
  $$SRC_DIR/AIMLib/AIMXML/type_iso.Cset_TelecommunicationAddressUse.h \
  $$SRC_DIR/AIMLib/AIMXML/type_xs.CENTITIES.h \
  $$SRC_DIR/AIMLib/AIMXML/type_xs.CENTITY.h \
  $$SRC_DIR/AIMLib/AIMXML/type_xs.CID.h \
  $$SRC_DIR/AIMLib/AIMXML/type_xs.CIDREF.h \
  $$SRC_DIR/AIMLib/AIMXML/type_xs.CIDREFS.h \
  $$SRC_DIR/AIMLib/AIMXML/type_xs.CNCName.h \
  $$SRC_DIR/AIMLib/AIMXML/type_xs.CNMTOKEN.h \
  $$SRC_DIR/AIMLib/AIMXML/type_xs.CNMTOKENS.h \
  $$SRC_DIR/AIMLib/AIMXML/type_xs.CNOTATION.h \
  $$SRC_DIR/AIMLib/AIMXML/type_xs.CName.h \
  $$SRC_DIR/AIMLib/AIMXML/type_xs.CQName.h \
  $$SRC_DIR/AIMLib/AIMXML/type_xs.CanySimpleType.h \
  $$SRC_DIR/AIMLib/AIMXML/type_xs.CanyType.h \
  $$SRC_DIR/AIMLib/AIMXML/type_xs.CanyURI.h \
  $$SRC_DIR/AIMLib/AIMXML/type_xs.Cbase64Binary.h \
  $$SRC_DIR/AIMLib/AIMXML/type_xs.Cbase64BinaryType.h \
  $$SRC_DIR/AIMLib/AIMXML/type_xs.Cboolean.h \
  $$SRC_DIR/AIMLib/AIMXML/type_xs.Cbyte.h \
  $$SRC_DIR/AIMLib/AIMXML/type_xs.Cdate.h \
  $$SRC_DIR/AIMLib/AIMXML/type_xs.CdateTime.h \
  $$SRC_DIR/AIMLib/AIMXML/type_xs.Cdecimal.h \
  $$SRC_DIR/AIMLib/AIMXML/type_xs.Cdouble.h \
  $$SRC_DIR/AIMLib/AIMXML/type_xs.Cduration.h \
  $$SRC_DIR/AIMLib/AIMXML/type_xs.Cfloat.h \
  $$SRC_DIR/AIMLib/AIMXML/type_xs.CgDay.h \
  $$SRC_DIR/AIMLib/AIMXML/type_xs.CgMonth.h \
  $$SRC_DIR/AIMLib/AIMXML/type_xs.CgMonthDay.h \
  $$SRC_DIR/AIMLib/AIMXML/type_xs.CgYear.h \
  $$SRC_DIR/AIMLib/AIMXML/type_xs.CgYearMonth.h \
  $$SRC_DIR/AIMLib/AIMXML/type_xs.ChexBinary.h \
  $$SRC_DIR/AIMLib/AIMXML/type_xs.Cint.h \
  $$SRC_DIR/AIMLib/AIMXML/type_xs.Cinteger.h \
  $$SRC_DIR/AIMLib/AIMXML/type_xs.Clanguage.h \
  $$SRC_DIR/AIMLib/AIMXML/type_xs.Clong.h \
  $$SRC_DIR/AIMLib/AIMXML/type_xs.CnegativeInteger.h \
  $$SRC_DIR/AIMLib/AIMXML/type_xs.CnonNegativeInteger.h \
  $$SRC_DIR/AIMLib/AIMXML/type_xs.CnonPositiveInteger.h \
  $$SRC_DIR/AIMLib/AIMXML/type_xs.CnormalizedString.h \
  $$SRC_DIR/AIMLib/AIMXML/type_xs.CpositiveInteger.h \
  $$SRC_DIR/AIMLib/AIMXML/type_xs.Cshort.h \
  $$SRC_DIR/AIMLib/AIMXML/type_xs.Cstring.h \
  $$SRC_DIR/AIMLib/AIMXML/type_xs.CstringType.h \
  $$SRC_DIR/AIMLib/AIMXML/type_xs.Ctime.h \
  $$SRC_DIR/AIMLib/AIMXML/type_xs.Ctoken.h \
  $$SRC_DIR/AIMLib/AIMXML/type_xs.CunsignedByte.h \
  $$SRC_DIR/AIMLib/AIMXML/type_xs.CunsignedInt.h \
  $$SRC_DIR/AIMLib/AIMXML/type_xs.CunsignedLong.h \
  $$SRC_DIR/AIMLib/AIMXML/type_xs.CunsignedShort.h \
  $$SRC_DIR/AIMLib/Altova/Altova.h \
  $$SRC_DIR/AIMLib/Altova/AltovaDefs.h \
  $$SRC_DIR/AIMLib/Altova/AltovaException.h \
  $$SRC_DIR/AIMLib/Altova/SchemaTypes.h \
  $$SRC_DIR/AIMLib/Altova/StdAfx.h \
  $$SRC_DIR/AIMLib/Altova/StructInfo.h \
  $$SRC_DIR/AIMLib/Altova/exception.h \
  $$SRC_DIR/AIMLib/Altova/xs-datetime.h \
  $$SRC_DIR/AIMLib/Altova/xs-types.h \
  $$SRC_DIR/AIMLib/AltovaXML/AltovaXMLAPI.h \
  $$SRC_DIR/AIMLib/AltovaXML/Node.h \
  $$SRC_DIR/AIMLib/AltovaXML/StdAfx.h \
  $$SRC_DIR/AIMLib/AltovaXML/XercesString.h \
  $$SRC_DIR/AIMLib/AltovaXML/XmlException.h

SOURCES += \
  $$SRC_DIR/AIMLib/AIMConverter/AIMConverter.cpp \
  $$SRC_DIR/AIMLib/AIMConverter/ConverterUtil.cpp \
  $$SRC_DIR/AIMLib/AIMConverter/stdafx.cpp \
  $$SRC_DIR/AIMLib/AIMLib/AIMCodes.cpp \
  $$SRC_DIR/AIMLib/AIMLib/AIMLib.cpp \
  $$SRC_DIR/AIMLib/AIMLib/AIMUtil.cpp \
  $$SRC_DIR/AIMLib/AIMLib/AimEnum.cpp \
  $$SRC_DIR/AIMLib/AIMLib/AimResultValidator.cpp \
  $$SRC_DIR/AIMLib/AIMLib/entity/AdjudicationObservation.cpp \
  $$SRC_DIR/AIMLib/AIMLib/entity/Algorithm.cpp \
  $$SRC_DIR/AIMLib/AIMLib/entity/AnnotationCollection.cpp \
  $$SRC_DIR/AIMLib/AIMLib/entity/AnnotationEntity.cpp \
  $$SRC_DIR/AIMLib/AIMLib/entity/AnnotationOfAnnotation.cpp \
  $$SRC_DIR/AIMLib/AIMLib/entity/AnnotationOfAnnotationCollection.cpp \
  $$SRC_DIR/AIMLib/AIMLib/entity/AnnotationRoleEntity.cpp \
  $$SRC_DIR/AIMLib/AIMLib/entity/AuditTrail.cpp \
  $$SRC_DIR/AIMLib/AIMLib/entity/CalculationData.cpp \
  $$SRC_DIR/AIMLib/AIMLib/entity/CalculationEntity.cpp \
  $$SRC_DIR/AIMLib/AIMLib/entity/CalculationResult.cpp \
  $$SRC_DIR/AIMLib/AIMLib/entity/CharacteristicQuantification.cpp \
  $$SRC_DIR/AIMLib/AIMLib/entity/CompactCalculationResult.cpp \
  $$SRC_DIR/AIMLib/AIMLib/entity/Coordinate.cpp \
  $$SRC_DIR/AIMLib/AIMLib/entity/DicomImageReferenceEntity.cpp \
  $$SRC_DIR/AIMLib/AIMLib/entity/DicomSegmentationEntity.cpp \
  $$SRC_DIR/AIMLib/AIMLib/entity/Dimension.cpp \
  $$SRC_DIR/AIMLib/AIMLib/entity/Entity.cpp \
  $$SRC_DIR/AIMLib/AIMLib/entity/Equipment.cpp \
  $$SRC_DIR/AIMLib/AIMLib/entity/ExtendedCalculationResult.cpp \
  $$SRC_DIR/AIMLib/AIMLib/entity/GeneralImage.cpp \
  $$SRC_DIR/AIMLib/AIMLib/entity/GeneralLesionObservationEntity.cpp \
  $$SRC_DIR/AIMLib/AIMLib/entity/GeometricShapeEntity.cpp \
  $$SRC_DIR/AIMLib/AIMLib/entity/Image.cpp \
  $$SRC_DIR/AIMLib/AIMLib/entity/ImageAnnotation.cpp \
  $$SRC_DIR/AIMLib/AIMLib/entity/ImageAnnotationCollection.cpp \
  $$SRC_DIR/AIMLib/AIMLib/entity/ImagePlane.cpp \
  $$SRC_DIR/AIMLib/AIMLib/entity/ImageReferenceEntity.cpp \
  $$SRC_DIR/AIMLib/AIMLib/entity/ImageSeries.cpp \
  $$SRC_DIR/AIMLib/AIMLib/entity/ImageStudy.cpp \
  $$SRC_DIR/AIMLib/AIMLib/entity/ImagingObservationCharacteristic.cpp \
  $$SRC_DIR/AIMLib/AIMLib/entity/ImagingObservationEntity.cpp \
  $$SRC_DIR/AIMLib/AIMLib/entity/ImagingPhysicalEntity.cpp \
  $$SRC_DIR/AIMLib/AIMLib/entity/ImagingPhysicalEntityCharacteristic.cpp \
  $$SRC_DIR/AIMLib/AIMLib/entity/InferenceEntity.cpp \
  $$SRC_DIR/AIMLib/AIMLib/entity/Interval.cpp \
  $$SRC_DIR/AIMLib/AIMLib/entity/LesionObservationEntity.cpp \
  $$SRC_DIR/AIMLib/AIMLib/entity/MarkupEntity.cpp \
  $$SRC_DIR/AIMLib/AIMLib/entity/NonQuantifiable.cpp \
  $$SRC_DIR/AIMLib/AIMLib/entity/Numerical.cpp \
  $$SRC_DIR/AIMLib/AIMLib/entity/Parameter.cpp \
  $$SRC_DIR/AIMLib/AIMLib/entity/Person.cpp \
  $$SRC_DIR/AIMLib/AIMLib/entity/Quantile.cpp \
  $$SRC_DIR/AIMLib/AIMLib/entity/ReferencedDicomObject.cpp \
  $$SRC_DIR/AIMLib/AIMLib/entity/Scale.cpp \
  $$SRC_DIR/AIMLib/AIMLib/entity/SegmentationEntity.cpp \
  $$SRC_DIR/AIMLib/AIMLib/entity/TaskContextEntity.cpp \
  $$SRC_DIR/AIMLib/AIMLib/entity/TextAnnotationEntity.cpp \
  $$SRC_DIR/AIMLib/AIMLib/entity/ThreeDimensionEllipse.cpp \
  $$SRC_DIR/AIMLib/AIMLib/entity/ThreeDimensionEllipsoid.cpp \
  $$SRC_DIR/AIMLib/AIMLib/entity/ThreeDimensionGeometricShapeEntity.cpp \
  $$SRC_DIR/AIMLib/AIMLib/entity/ThreeDimensionMultiPoint.cpp \
  $$SRC_DIR/AIMLib/AIMLib/entity/ThreeDimensionPoint.cpp \
  $$SRC_DIR/AIMLib/AIMLib/entity/ThreeDimensionPolygon.cpp \
  $$SRC_DIR/AIMLib/AIMLib/entity/ThreeDimensionPolyline.cpp \
  $$SRC_DIR/AIMLib/AIMLib/entity/ThreeDimensionSpatialCoordinate.cpp \
  $$SRC_DIR/AIMLib/AIMLib/entity/TimePointLesionObservationEntity.cpp \
  $$SRC_DIR/AIMLib/AIMLib/entity/TwoDimensionCircle.cpp \
  $$SRC_DIR/AIMLib/AIMLib/entity/TwoDimensionEllipse.cpp \
  $$SRC_DIR/AIMLib/AIMLib/entity/TwoDimensionGeometricShapeEntity.cpp \
  $$SRC_DIR/AIMLib/AIMLib/entity/TwoDimensionMultiPoint.cpp \
  $$SRC_DIR/AIMLib/AIMLib/entity/TwoDimensionPoint.cpp \
  $$SRC_DIR/AIMLib/AIMLib/entity/TwoDimensionPolyline.cpp \
  $$SRC_DIR/AIMLib/AIMLib/entity/TwoDimensionSpatialCoordinate.cpp \
  $$SRC_DIR/AIMLib/AIMLib/entity/UriImageReferenceEntity.cpp \
  $$SRC_DIR/AIMLib/AIMLib/entity/User.cpp \
  $$SRC_DIR/AIMLib/AIMLib/external/CD.cpp \
  $$SRC_DIR/AIMLib/AIMLib/external/II.cpp \
  $$SRC_DIR/AIMLib/AIMLib/operations/BaseModel.cpp \
  $$SRC_DIR/AIMLib/AIMLib/operations/DcmModel.cpp \
  $$SRC_DIR/AIMLib/AIMLib/operations/DcmModelInternalRead.cpp \
  $$SRC_DIR/AIMLib/AIMLib/operations/DcmModelInternalWrite.cpp \
  $$SRC_DIR/AIMLib/AIMLib/operations/DicomTagCollection.cpp \
  $$SRC_DIR/AIMLib/AIMLib/operations/ModelValidator.cpp \
  $$SRC_DIR/AIMLib/AIMLib/operations/XmlModel.cpp \
  $$SRC_DIR/AIMLib/AIMLib/operations/XmlModelInternalRead.cpp \
  $$SRC_DIR/AIMLib/AIMLib/operations/XmlModelInternalWrite.cpp \
  $$SRC_DIR/AIMLib/AIMLib/statement/StatementFactory.cpp \
  $$SRC_DIR/AIMLib/AIMLib/stdafx.cpp \
  $$SRC_DIR/AIMLib/AIMLib/util/AimUidGenerator.cpp \
  $$SRC_DIR/AIMLib/AIMLib/util/DateTime.cpp \
  $$SRC_DIR/AIMLib/AIMXML/AIMXML-typeinfo.cpp \
  $$SRC_DIR/AIMLib/AIMXML/AIMXML.cpp \
  $$SRC_DIR/AIMLib/AIMXML/StdAfx.cpp \
  $$SRC_DIR/AIMLib/Altova/AltovaException.cpp \
  $$SRC_DIR/AIMLib/Altova/SchemaTypes.cpp \
  $$SRC_DIR/AIMLib/Altova/StdAfx.cpp \
  $$SRC_DIR/AIMLib/Altova/StructInfo.cpp \
  $$SRC_DIR/AIMLib/Altova/xs-datetime.cpp \
  $$SRC_DIR/AIMLib/Altova/xs-types.cpp \
  $$SRC_DIR/AIMLib/AltovaXML/Node.cpp \
  $$SRC_DIR/AIMLib/AltovaXML/StdAfx.cpp \
  $$SRC_DIR/AIMLib/AltovaXML/XmlException.cpp


message(choice: $$CPP_ROOT_DIR/targets/$$CHOICE_CODE/$$PROJECT_SET--$$PROJECT_GROUP--$$PROJECT_NAME)
mkpath($$CPP_ROOT_DIR/targets/$$CHOICE_CODE/$$PROJECT_SET--$$PROJECT_GROUP--$$PROJECT_NAME)
