/*
 *  mod_helloworld.c -- Apache sample helloworld module
 *  [Autogenerated via ``apxs -n helloworld -g'']
 *
 *  To play with this sample module first compile it into a
 *  DSO file and install it into Apache's modules directory
 *  by running:
 *
 *    $ apxs -c -i mod_helloworld.c
 *
 *  Then activate it in Apache's httpd.conf file for instance
 *  for the URL /helloworld in as follows:
 *
 *    # httpd.conf
 *    LoadModule helloworld_module modules/mod_helloworld.so
 *    <Location /hello>
 *      SetHandler helloworld
 *    </Location>
 *
 *  Then after restarting Apache via
 *
 *    $ apachectl restart
 *
 *  you immediately can request the URL /helloworld and watch for the
 *  output of this module. This can be achieved for instance via:
 *
 *    $ lynx -mime_header http://localhost/hello
 */

#include "httpd.h"
#include "http_config.h"
#include "http_protocol.h"
#include "ap_config.h"

#include "qmt-utils/qmt-utils.h"

// request handler example
// request_rec Struct Reference
// http://ci.apache.org/projects/httpd/trunk/doxygen/structrequest__rec.html

static int qmt_handler(request_rec *req)
{
 void* details = NULL;
 int positive_response = 0;

 int r = _parse_url_via_start("-qmt-handler", req->uri, "/qmt", &positive_response, DECLINED, &details);
 if(positive_response == 0)
 {
  return r;
 }
 if (req->header_only)
 {
  //?
 }
 else
 {
  char** fields;

  int sz = get_response_array(details, &fields, "-qmt-response-array");

  char msg[16];
  sprintf(msg, "sz: %d\n", sz);
  log_comments("-qmt-handler", msg);

//  char msg1[70];
//  sprintf(msg, "sz: %s", fields);
//  log_comments("-qmt-handler", msg);

  if(sz == 0)
    ap_rputs(fields[1], req);
  else
    ap_rwrite(fields[0], sz, req);

  req->content_type = fields[1]; // "text/html;charset=UTF-8";
 }

 //? apr_table_set(req->headers_out, "X-Content-Type-Options", "nosniff");

 return OK;
}

static void qmt_register_hooks(apr_pool_t *p)
{
    printf("\n ** qmt_register_hooks  **\n\n");
    ap_hook_handler(qmt_handler, NULL, NULL, APR_HOOK_MIDDLE);
}

/* Dispatch list for API hooks */
module AP_MODULE_DECLARE_DATA qmt_module = {
    STANDARD20_MODULE_STUFF,
    NULL, /* create per-dir    config structures */
    NULL, /* merge  per-dir    config structures */
    NULL, /* create per-server config structures */
    NULL, /* merge  per-server config structures */
    NULL, /* table of config file commands       */
    qmt_register_hooks  /* register hooks */
};
